### ISSUE TITLE
I'm in ShenZhen 

### ISSUE THREAD

**Issue by jeongm-in** [jeongm/UVACS1110-#10]
Didn't know there're no such thing as Facebook, Google, Twitter, Instagram etc in China.
Everything I do on internet was so Google heavy, I don't know what to do. 
Guess it's high time I get away from internet addiction? 
I do remember some Chinese back from high school days, but those are all mixed up with Japanese. Terrible, terrible. 
I cannot pronounce pinyin properly.. Would people understand?
But with little Chinese I could speak I made some progress. Other grad students and professors paid 300 and 400 yuan each for taxi ride to hotel. 
But I spoke something like wo men xiang qu zher... And showed driver the address. 
Result? 73 yuan. # Pray for grad studenrs

**Comment by jeongm-in** [comment]
I experienced something scary.
I was reading webtoon at naver, and some Chinese on screen pop up window appeared. Something like on-page advertisement block? 
I tried to dismiss it, but it tried to download some apk file. Considering the fact that naver webtoon doesn't have any advertisements...

**Comment by jeongm-in** [comment]
What does 如手机无法接收短信请联系服务人员获取账号及密码 mean? Looks like something related to cell phone and SMS authentication. 
There is no free wifi in China. Even one in Starbucks you should authenticate with shouji

**Comment by Bartleby2718** [comment]
ㅇㅎ 이렇게 하며 코드를 더럽히지 않을 수 있구만
구글 번역이 의외로 정확하게 잘되네
"If the phone can not receive SMS, please contact service personnel for account number and password"
如 / 手机 / 无法 / 接收 / 短信 / 请 / 联系 / 服务 / 人员 / 获取 / 账号 / 及 / 密码를
직역해 보면 아마
like / cell phone / can't / receive / SMS / please / contact / service / personnel / get / account number / and / password
일 거임

**Comment by jeongm-in** [comment]
와 service personnelㅋㅋㅋㅋ 답도없다 
Github is my favorite SNS from now on...

**Comment by jeongm-in** [comment]
자동 로그인 비밀번호 저장은 브라우저단위로 저장하는 데이터인지 구글이 안 되도 로그인은 되는군

**Comment by Bartleby2718** [comment]
아 지금 보니 如가 如果(if)의 준말이네

**Comment by jeongm-in** [comment]
중국에 살면 좋든 싫든 중국어를 배울 수 밖에 없겠다는 생각을 했음

**Comment by Bartleby2718** [comment]
그래서 강제로라도 유학을 보내는 듯

**Comment by jeongm-in** [comment]
Sent email to bartleby2718@gmail.com
Plz check

**Comment by jeongm-in** [comment]
Kakaotalk suddenly not working at day 4
Conference is over.

**Comment by jeongm-in** [comment]
I am back from Shenzhen, so close Issue #10
