### ISSUE TITLE
Jeong-Min PA13 : higher_lower_player.py

### ISSUE THREAD

**Issue by jeongm-in** [jeongm/UVACS1110-#11]
d081e23 
Finished basic frame. 
TODO : how to test if user is lying or being inconsistent?

**Comment by Bartleby2718** [comment]
커밋 메시지에 # 써서 연결하는 게 나음

**Comment by Bartleby2718** [comment]
1. Contradiction found during the game
- If there are contradicting conditions -> `Wait; how can it be both (condition1) and (condition2)?`
  - Conditions must be stored in a list
2. Contradiction found after the game is over
- If there is a condition that is not satisfied by the answer ->  `That can't be; you said it was (condition)!`
  - It should be checked that the allged answer satisfies all the conditions in the list.
3. TQ1
- Use `in`, `.lower()`, and `.strip()` to deal with not-quite-right user inputs
4. TQ2
- `answer_range` is nonempty but contains no integer

**Comment by Bartleby2718** [comment]
1. condition을 string literal로 하면
- `list_of_conditions = ['<50', '>25', '<37', '>31', '<34']`
`if eval(answer + condition)` 이렇게 할 거 같고
2. condition을 tuple of string and int로 하면
- `list_of_conditions = [('<', 50), ('>', 25), ('<', 37), ('>', 31), ('<', 34)]`
`for condition in list_of_conditions:`...
`operator, operand = condition` (사실 나도 tuple 안 써서 이 문법 알면서도 써 본 적은 없음)
`if operator == '<' and answer < operand:`...
`elif operator == '>' and answer > operand:`...
`else:`... 이렇게 할 거 같고

**Comment by Bartleby2718** [comment]
참고로 커밋이나 이슈에 코멘트 쓸 때 Shift+Enter = 다음 줄로, Ctrl+Enter -> submit임
