### ISSUE TITLE
Jihoon PA13 - class 이용해서

### ISSUE THREAD

**Issue by Bartleby2718** [jeongm/UVACS1110-#13]

**Comment by Bartleby2718** [comment]
저거 ㅅㅂ #12 인데 잘못 썼네

**Comment by Bartleby2718** [comment]
@jeongm 
`higher_lower_player.py`랑 `hlp_class_int.py`랑 대부분의 코드가 같긴 한데, 다른 부분 봤을 때 class 쓴 게 나음, 안 쓴 게 나음?

**Comment by jeongm-in** [comment]
ㅎ.. ㅎ 제가 object oriented에 좀 약해서요... 14년 임정민은 이해할수있었을텐데 17임정민은 못할듯

**Comment by jeongm-in** [comment]
한번 읽어보고 다시달겠음

**Comment by Bartleby2718** [comment]
@jeongm 안 읽어볼 거 같으니 걍 닫겠음

**Comment by jeongm-in** [comment]
읽어봄
