### ISSUE TITLE
git commit --amend

### ISSUE THREAD

**Issue by Bartleby2718** [jeongm/UVACS1110-#14]
https://stackoverflow.com/questions/179123/how-to-modify-existing-unpushed-commits

**Comment by jeongm-in** [comment]
What about pushed commits? I know I should re check before pushing, but....
Looks like there are lots of red flags sticking up for force-pushing.

**Comment by Bartleby2718** [comment]
ㅇㅇ 가급적이면 할 일이 없어야겠지만 한다면 -f flag 넣어서 해야 하는 듯

**Comment by Bartleby2718** [comment]
@jeongm https://stackoverflow.com/questions/927358/how-to-undo-the-last-commits-in-git?page=1&tab=votes#tab-top
