### ISSUE TITLE
Jeong-Min, Roman.py

### ISSUE THREAD

**Issue by jeongm-in** [jeongm/UVACS1110-#15]
I figured I need to use String concatenation for this assignment.
As I am also poking at algorithms I realized both memory and speed-wise efficiency is important.
[Efficient String Concatenation in Python](https://waymoot.org/home/python_string/)
suggests that list comprehension method is far more efficient than five other methods. 
Although Roman.py does not process such large amounts of data, I believe using efficient string concatenation method is a better practice. 

BUT I didn't use above method for this assignment.

**Comment by jeongm-in** [comment]
- [ ] use modular operation (%) for each Roman numerals 

- [ ] concatenate corresponding Roman numerals to answer value

- [x] might also try using [divmod(x, y) which returns tuple (x / y, x % y) ](https://stackoverflow.com/a/992639/8776165)

**Comment by jeongm-in** [comment]
How to check number is in range  :

- [ ]  ` if number in range(4000)`

- [x]  `if number < 0 or number > 4000`

case 2 is better, as it only involves two simple logical comparisons

**Comment by jeongm-in** [comment]
How to extract Roman numerals

- [x] use dictionary as iterator for for loop

- [x] how to handle 90 (XC), 4(IV), etc
Maybe run another loop to check if IIII or XXXX occurs in list, then convert to IV and XC

Also
>roman_numeric = ''.join('M' for num in range(how_many_M[0]))
>roman_numeric = roman_numeric.join('D' for num in range(how_many_D[0]))

does not update roman_numeric, [references to values issue](https://stackoverflow.com/a/8744234/8776165)

- [x] potential solution : append everything into list and then join them at the end of the program?

**Comment by jeongm-in** [comment]
Finished roman.py 1dd6bcc
(forgot to mention #15 in commit message)
Well, assignment asked students to write code as compact as possible. 
Mine is far from compact. 
- [ ] simplify?

**Comment by Bartleby2718** [comment]
1) 논리적으로 `number in range(1, 4000)`랑
`isinstance(number, int) and number > 0 and number < 4000` 완전히 같으니 리스트 하나를 다 돌아볼 필요는 없지 ㅇㅇ

**Comment by Bartleby2718** [comment]
2) int는 str() 함수를 통해 str이 될 수 있으니(&vice versa)  int로 잘 안되면 스트링으로 바꿔보는 것(&vice versa)도 방법인 듯
