### ISSUE TITLE
What is __pycache__?

### ISSUE THREAD

**Issue by Bartleby2718** [jeongm/UVACS1110-#2]
- 앞으로는 https://github.com/jeongm/UVACS1110-/commit/0ff0f0f299aed3580c9206365915842cc4d2aaae 에서처럼 커밋 메시지로 질문하지 말고 이렇게 이슈 만드셈셈~ (아니면 여기에 써 놓고 나중에 직접 검색하든지)

**Comment by jeongm-in** [comment]
how do you link 16bfc0a like that?

**Comment by jeongm-in** [comment]
#16bfc0a 
huh github automatically links that for me

**Comment by Bartleby2718** [comment]
ㅇㅇ 그냥 full URL 올리면 깃헙이 알아서 줄여줌
그리고 # 쓰는 건 issue 링크할 때만 쓸 수 있음
근데 왜 pycache가 뭔지 안 나왔는데 닫았냨

**Comment by jeongm-in** [comment]
Pycache 말그대로 python Code compile 할 때 나오는 임시파일 같은거라드라고
