### ISSUE TITLE
Debug Lab Endgame Behavior

### ISSUE THREAD

**Issue by jeongm-in** [jeongm/UVACS1110-#24]
When running the program, once marbles reaches 1, the game ends automatically (Computer wins).
However in the lab assignment, the program is supposed to ask user to pick a marble, and then ends the game. 
```
The number of marbles in the pile: 1
Who will start? (p or c): p
The pile has 1 marbles in it.
The computer wins!
```
- [ ] fix abrupt endgame bug, letting user pick the marble of defeat himself

**Comment by Bartleby2718** [comment]
엥 그럼 나도 틀렸나 보네
밥 먹고 와서 보겠음

**Comment by Bartleby2718** [comment]
@jeongm ㅇㄴ close뿐만 아니라 fix로도 닫히는구나
이렇게 하니까 되네염
