### ISSUE TITLE
Regex

### ISSUE THREAD

**Issue by jeongm-in** [jeongm/UVACS1110-#25]
Q: Is it meant to make one regex that matches all? 

helpful resources
1. https://www.regexpal.com/ : shows how a regex matches a piece of text you enter

Flow : 
the code reads every line of the text
modify each line for each cases and pass it on
find email address

**Comment by jeongm-in** [comment]
http://cs1110.cs.virginia.edu/emails.html
- [x] basic@virginia.edu
- [x] link-only@virginia.edu
- [x] multi-domain@cs.virginia.edu
- [x] Mr.N0body@cand3lwick-burnERS.rentals
- [x] a@b.ca
- [x] no-at-sign@virginia.edu
- [x] no-at-or-dot@virginia.edu
- [x] first.last.name@cs.virginia.edu
- [x] with-parenthesis@Virginia.EDU
- [x] added-words1@virginia.edu
- [x] added-words2@virginia.edu
- [x] may.end@with-a-period.com
- [x] underscore@virginia.edu
- TODO: refine code (replace _ with string[-3])
- [x] reverse@virginia.edu
- attempt using decoded[::-1] returns wrong-in-context but valid-in-format email addresses
  - (ex: slatner.SREnrub-kciwl3dnac@ydob0N.rM)
  - [x] how to distinguish random gibberish from legit reverse-formatted text
    - if 'reverse' is in line: reverse-slice text 
- [x] ~~JohnDoe@virginia.edu~~ JohnD@virginia.edu __(#18)__
  - [x] if 'initial' is in line: use regex object to find name
- [x] markdown@virginia.edu
- [x] refine code (nasty messy formatting to decode markdown)
  - markdown randomly formats char between HEX and DEC.
  - letter encoded in HEX has x prefix
  - use another regex object? 
  - [x] use re.sub with function @Bartleby2718 
    - [re.sub](https://docs.python.org/2/library/re.html#re.sub)




<details><summary>emails.php</summary><p>

http://cs1110.cs.virginia.edu/emails.php

- [x] one@two.com
- [x] three-four@five.edu
- [x] six-seven@cs.virginia.edu
- [x] Mrs.N0way@l4rd-frAMers.info
- [x] d@e.tv
- [x] with-at-sign@vt.edu
- [x] other-email@virginia.com
- [x] ~~first.name@seas.virginia.edu~~ last.first.name@seas.virginia.edu __(#18)__
- [x] my-little@PoNy.ORG
- [x] king@queen.gov
- [x] prince@princess.uk
- [x] a.b@c.d.e.com
- [x] alligator@gmail.com
- [x] backwards@virginia.com
- [x] JaneR@virignia.edu
- [x] moo@cow.com

</p></details>

**Comment by jeongm** [comment]
most recent commit : e8fdd89

**Comment by jeongm** [comment]
I guess methods I used for "ridiculous ones for bragging rights:" are hardcoding.
What is your opinion?

**Comment by Bartleby2718** [comment]
ㅅㅂ 이걸 이제야 봤네
아니 존도는 그냥 어이가 없네 ㅋㅋㅋ 어쩌란 거지
