### ISSUE TITLE
Budget web hosting

### ISSUE THREAD

**Issue by jeongm-in** [jeongm/UVACS1110-#26]
I know this is random, but I found a budget web [hosting service](http://teamjang.com/sub1_01_guide.html
) to play with. 
- 3000 KRW / year for 300MB storage and 500MB traffic / day
- free .zc.bz domain

**Comment by jeongm** [comment]
* [Airbnb](https://play.google.com/store/apps/details?id=com.airbnb.android) 
* [Amazon Kindle](https://play.google.com/store/apps/details?id=com.amazon.kindle) 
* [Android Wear](https://play.google.com/store/apps/details?id=com.google.android.wearable.app) 
* [ASAP Launcher](https://play.google.com/store/apps/details?id=com.citc.asap) 
* [Boost](https://play.google.com/store/apps/details?id=com.rubenmayayo.reddit) 
* [Calendar](https://play.google.com/store/apps/details?id=com.google.android.calendar) 
* [Camera](https://play.google.com/store/apps/details?id=com.google.android.GoogleCamera) 
* [CGV](https://play.google.com/store/apps/details?id=com.cgv.android.movieapp) 
* [Contacts](https://play.google.com/store/apps/details?id=com.google.android.contacts) 
* [Discord](https://play.google.com/store/apps/details?id=com.discord) 
* [Facebook](https://play.google.com/store/apps/details?id=com.facebook.katana) 
* [Find My Device](https://play.google.com/store/apps/details?id=com.google.android.apps.adm) 
* [Forest](https://play.google.com/store/apps/details?id=cc.forestapp) 
* [Graph 89](https://play.google.com/store/apps/details?id=com.Bisha.TI89EmuDonation) 
* [Hangouts](https://play.google.com/store/apps/details?id=com.google.android.talk) 
* [Hearthstone](https://play.google.com/store/apps/details?id=com.blizzard.wtcg.hearthstone) 
* [Home](https://play.google.com/store/apps/details?id=com.google.android.apps.chromecast.app) 
* [IFTTT](https://play.google.com/store/apps/details?id=com.ifttt.ifttt) 
* [Inbox](https://play.google.com/store/apps/details?id=com.google.android.apps.inbox) 
* [indistreet](https://play.google.com/store/apps/details?id=com.indistreet.indistreet) 
* [Instagram](https://play.google.com/store/apps/details?id=com.instagram.android) 
* [Kakao T](https://play.google.com/store/apps/details?id=com.kakao.taxi) 
* [KakaoBus](https://play.google.com/store/apps/details?id=com.astroframe.seoulbus) 
* [KakaoMetro](https://play.google.com/store/apps/details?id=net.orizinal.subway) 
* [KakaoTalk](https://play.google.com/store/apps/details?id=com.kakao.talk) 
* [Keep](https://play.google.com/store/apps/details?id=com.google.android.keep) 
* [Lezhin Comics](https://play.google.com/store/apps/details?id=com.lezhin.comics) 
* [Messenger Lite](https://play.google.com/store/apps/details?id=com.facebook.mlite) 
* [MX Player](https://play.google.com/store/apps/details?id=com.mxtech.videoplayer.ad) 
* [My Maps](https://play.google.com/store/apps/details?id=com.google.android.apps.m4b) 
* [NAVER](https://play.google.com/store/apps/details?id=com.nhn.android.search) 
* [Naver Map](https://play.google.com/store/apps/details?id=com.nhn.android.nmap) 
* [Naver Music](https://play.google.com/store/apps/details?id=com.nhn.android.music) 
* [NOWA](https://play.google.com/store/apps/details?id=smart.AP0067) 
* [Obsqr](https://play.google.com/store/apps/details?id=trikita.obsqr) 
* [Papago](https://play.google.com/store/apps/details?id=com.naver.labs.translator) 
* [Pebble](https://play.google.com/store/apps/details?id=com.getpebble.android.basalt) 
* [PlayStation](https://play.google.com/store/apps/details?id=com.scee.psxandroid) 
* [Root Explorer](https://play.google.com/store/apps/details?id=com.speedsoftware.rootexplorer) 
* [SCViewer](https://play.google.com/store/apps/details?id=com.cattowersoft.scv) 
* [Snapchat](https://play.google.com/store/apps/details?id=com.snapchat.android) 
* [SoundHound ∞](https://play.google.com/store/apps/details?id=com.melodis.midomiMusicIdentifier) 
* [SR 고속열차](https://play.google.com/store/apps/details?id=kr.co.srail.app) 
* [Star Chart](https://play.google.com/store/apps/details?id=com.escapistgames.starchart) 
* [SwiftKey Keyboard](https://play.google.com/store/apps/details?id=com.touchtype.swiftkey) 
* [Syrup 월렛](https://play.google.com/store/apps/details?id=com.skt.skaf.OA00026910) 
* [S알리미](https://play.google.com/store/apps/details?id=com.shinhan.smartcaremgr) 
* [Toss](https://play.google.com/store/apps/details?id=viva.republica.toss) 
* [Translate](https://play.google.com/store/apps/details?id=com.google.android.apps.translate) 
* [T스팸필터링](https://play.google.com/store/apps/details?id=com.skt.skaf.OA000292101) 
* [T인증](https://play.google.com/store/apps/details?id=com.sktelecom.tauth) 
* [YouTube Music](https://play.google.com/store/apps/details?id=com.google.android.apps.youtube.music) 
* [네이버 클로바](https://play.google.com/store/apps/details?id=com.naver.nozzle) 
* [롯데시네마](https://play.google.com/store/apps/details?id=kr.co.lottecinema.lcm) 
* [메가박스](https://play.google.com/store/apps/details?id=com.megabox.mop) 
* [뱅크샐러드](https://play.google.com/store/apps/details?id=com.rainist.banksalad2) 
* [삼성증권 mPOP](https://play.google.com/store/apps/details?id=com.samsungpop.android.mpop) 
* [신한 FAN
(앱카드)](https://play.google.com/store/apps/details?id=com.shcard.smartpay) 
* [신한S뱅크](https://play.google.com/store/apps/details?id=com.shinhan.sbanking) 
* [신한카드](https://play.google.com/store/apps/details?id=com.shinhancard.smartshinhan) 
* [써니뱅크](https://play.google.com/store/apps/details?id=com.shinhan.speedup) 
* [웨더퐁
날씨위젯](https://play.google.com/store/apps/details?id=com.skplanet.weatherpong.mobile) 
* [카카오뱅크](https://play.google.com/store/apps/details?id=com.kakaobank.channel) 
* [코레일톡](https://play.google.com/store/apps/details?id=com.korail.talk) 

List made using [List My Apps](https://play.google.com/store/apps/details?id=de.onyxbits.listmyapps)

**Comment by Bartleby2718** [comment]
? 네가 갖고 있는 모든 앱데스까

**Comment by jeongm** [comment]
Yeah I backed up app list because I needed to reset my phone
