### ISSUE TITLE
PA 09: averages.py - Jihoon

### ISSUE THREAD

**Issue by Bartleby2718** [jeongm/UVACS1110-#3]

**Comment by Bartleby2718** [comment]
어떻게 해야 할지 감이 안 왔는데 [Troubleshooting 섹션](https://cs1110.cs.virginia.edu/pa09-averages.html#troubleshooting)을 보니 "Your median function will probably need several if statements."라고 써 있음.

**Comment by jeongm-in** [comment]
이거 하기는 했는데 결과물이 마음에 안 듦
좀 더 제네릭 한 함수를 짜고 싶었는데 그렇게 쉽게 안 되는군

**Comment by Bartleby2718** [comment]
커밋 메시지를 "close #3 Finished averages.py"라고 썼으면 알아서 close까지 했었을 텐데 실수...

**Comment by Bartleby2718** [comment]
@jeongm 거기에 코멘트 달았음
실제로 프로젝트 진행할 때는 이런 식으로 GitHub의 issue를 이용한다는 걸 보여주려고 만들어 봄
