### ISSUE TITLE
PA 10: calculator.py - Jihoon

### ISSUE THREAD

**Issue by Bartleby2718** [jeongm/UVACS1110-#4]

**Comment by jeongm-in** [comment]
이 이슈는 어떤 목적으로 열었음??

**Comment by Bartleby2718** [comment]
예전에 일할 때 이런 식으로 이슈 열어서 뭐할 건지 기록하고
커밋할 때 Close로 닫았음

**Comment by Bartleby2718** [comment]
>#### 3. Thought Questions
>How hard would it be to
>
>- Return the number if all there is is one number?
>- Deal with negative numbers too, like `-123 - -456`
>- Deal with a string with two operators, like `1 + 23 * 456`?


regex를 이용하는 방법 말고는 모르겠음

**Comment by Bartleby2718** [comment]
아... 알겠다...? recursion을 이용하면 되네;
- 연산자가 없으면 return
- 연산자가 있으면 binop(operand1)과 binop(operand2)를 그 연산자로 이음
  - `-`가 마이너스 부호가 아니라 뺄셈 기호임을 판단하려면 split 결과 앞에 숫자가 있는지 확인하면 됨
  - 우선 순위가 낮은 `+`, `-`부터 계산

**Comment by Bartleby2718** [comment]
아니 시발 너무 어렵잖아? 
`-1 - -1 * -1` 이걸 어떻게 풀지

**Comment by jeongm-in** [comment]
count how many -s are in there?
        # 1. A - B : only one - sign and - sign not at 0
        # 2. -A - B : two - signs and -sign at 0
        # 3. A - -B : two - signs and -sign not at 0
        # 4. -A - -B : three - signs and -sign at 0

**Comment by Bartleby2718** [comment]
@jeongm 네가 원하던 generic한 답을 찾은 듯하다
