### ISSUE TITLE
What is Markdown?

### ISSUE THREAD

**Issue by jeongm-in** [jeongm/UVACS1110-#6]
Refer to: http://kirkstrobeck.github.io/whatismarkdown.com/
> It's an easy way to write text that easily translates into HTML.

There's also a tool called __Markdown Extra__ (http://michelf.com/projects/php-markdown/extra/)

**Comment by Bartleby2718** [comment]
나중에 이슈 중에서 question이나 FYI 같은 레이블만 모아서 검색해 보면 복습하기 좋을 듯
