### ISSUE TITLE
unintentional push to master

### ISSUE THREAD

**Issue by jeongm-in** [jeongm/UVACS1110-#8]
example : b209543, 9c91f1d
Like @Bartleby2718 commented in 9c91f1d, test.py file was added to commit and then pushed together with the file I intended to push. 

I added calculator.py and ran _git commit_ with comments. 

This threw 
>[master b209543] Commit to continue working on different platform
> 2 files changed, 62 insertions(+), 36 deletions(-)
> rewrite sogogibeef/calculator.py (69%)
> create mode 100644 sogogibeef/test.py

when I ran _git status_, following message showed up.

>Changes not staged for commit:
>    (use "git add <file>..." to update what will be committed)
>    (use "git checkout -- <file>..." to discard changes in working directory)
>        modified:   sogogibeef/test.py

I thought only calculator.py added for publish, but apparently blank test.py was pushed as well.

But as seen above mode 100644 test.py was created, which is a blank file.

what should I do to keep local file that I do not wish to push to master? 

and is keeping a local file a good practice?

**Comment by Bartleby2718** [comment]
음 이건 네가 정확히 뭘 했는지는 알아야 하는데
`git commit`할 때 어떤 파일들을 `git add`한 상태였던 거임?
추정컨대 1) calculator.py 수정, 2) test.py 생성(코드는 X), 3) `git add .` 같은 명령을 통해 두 파일 모두 `git add`, 4) `git commit`, `git push`해서 test.py도 commit에 포함
이렇게 된 듯? 그냥 애초에 add를 안하면 그런 파일 있어도 상관 없음.

**Comment by jeongm-in** [comment]
git add 는 calculator.py만 했으 git add .는 안했지 
그래서 add 한 다음에 git status 쳤을때는 test.py는 안 올라가있었던걸 확인했는데 ...

**Comment by Bartleby2718** [comment]
나중에 똑같은 현상이 발생했을 때 명령어까지 해서 그대로 알려주셈
일단은 포기

**Comment by jeongm-in** [comment]
냉 나도 이거 사실 잘 몰름 ㅎ헿ㅅ!

**Comment by jeongm-in** [comment]
다시 일어나서 붙여봅니다 
상황은 비행기에서 roman.py를 하려다가 roman테이블이 없어서 credit_card.py를 먼저 작업한 상황
빈 파일 roman.py는 내 로컬 repo에 있고 credit_card.py를 어느정도 작업하고선 데스크탑에서 마저 하려고 깃에다가 올리려는 의도로 커밋하였음 

```
Jeongs-MacBook-Pro:sogogibeef jeongminlim$ git add credit_card.py
Jeongs-MacBook-Pro:sogogibeef jeongminlim$ git commit -m "Initial commit for credit_card.py"
[master 5724c7a] Initial commit for credit_card.py
 2 files changed, 51 insertions(+)
 create mode 100644 sogogibeef/credit_card.py
 create mode 100644 sogogibeef/roman.py 
```
↑ 여기 보면 add credit_card.py만 했는데 roman.py mode 가 생성됐음
```
Jeongs-MacBook-Pro:sogogibeef jeongminlim$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
```
↑ 이 커맨드를 써서
```
	modified:   calculator.py
	modified:   roman.py
	modified:   test.py

no changes added to commit (use "git add" and/or "git commit -a")
Jeongs-MacBook-Pro:sogogibeef jeongminlim$ git checkout -- test.py
Jeongs-MacBook-Pro:sogogibeef jeongminlim$ git checkout -- roman.py

Jeongs-MacBook-Pro:sogogibeef jeongminlim$ git status
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   calculator.py

no changes added to commit (use "git add" and/or "git commit -a")
Jeongs-MacBook-Pro:sogogibeef jeongminlim$ git push
Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 993 bytes | 993.00 KiB/s, done.
Total 4 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/jeongm/UVACS1110-.git
   375c17b..5724c7a  master -> master
```

그리고 결과적으론 예전처럼 빈 쭉정이 roman.py가 생성되어부렀음 
아니 미쳐요~~~~ 그러면 무조건 한번에 한 파일만 작업하고 커밋 한 다음에 다른 파일편집해야 한다는 건가?

**Comment by jeongm-in** [comment]
[How to remove file from staging area](https://stackoverflow.com/a/1505968/8776165)

[git reset command](http://schacon.github.io/git/git-reset.html)

**Comment by Bartleby2718** [comment]
원인을 알아낸 것 같다
![image](https://user-images.githubusercontent.com/7676354/34255159-ac6a0b30-e692-11e7-8d80-ab3a85c312ec.png)
파이참 가서 이 설정 확인해 보셈셈

**Comment by jeongm-in** [comment]
덜덜덜 켜져있기는 하네 근데 또 요새는 이런 일이 없음

**Comment by jeongm-in** [comment]
http://data.agaric.com/undo-git-add-remove-files-staged-git-commit
