### ISSUE TITLE
How to use while statements

### ISSUE THREAD

**Issue by jeongm-in** [jeongm/UVACS1110-#9]
in line 14 of 5a3ba2f 
I used 
> if user_input == answer:
>    break

Should I use 
> is_correct_guess = True

instead of break statement? 

Which is a better practice

**Comment by jeongm-in** [comment]
Again in 9fb1fd3 Line 9 and 20, 
I used False condition for while loops. 
If I were to use break statements to exit while loops, should I even declare and use 
> user_input_is_valid = False 
> while user_input_is_valid == False: 

for loop conditionals????? 
To elaborate, why not do 
> while False: 

if I were to use break statements to exit loops, rather than setting

>user_input_is_valid = True

**Comment by Bartleby2718** [comment]
아래 질문이 더 쉬우니 아래 질문부터.
`while False:`로 하면 infinite loop이 형성됨. 하지만 variable을 이용하면 그 variable의 값이 바뀌었을 때부터 loop이 멈춤. 이 때 쓰이는 (boolean?) variable을 flag라고 함.
이 코드에서는 `user_input_is_valid`라는 flag를 이용해서 loop이 언제 끝날지를 결정하는 거

**Comment by jeongm-in** [comment]
그러면 break로 나가지 말고 flag로 하는게 낫다는 것임?

**Comment by Bartleby2718** [comment]
ㅇㅋ 처음 질문에도 답을 해 줌. `is_correct_guess = True`를 하면 다음 loop 때 나오니까 1) 그동안 불필요한 연산을 거치거나 2) 그 loop를 따라가야 돼서 머리가 복잡해짐. 그래서 [나](https://github.com/jeongm/UVACS1110-/commit/de2e3e5a684d3149d18b124fad397c3a4a5fc25f)도 [너](https://github.com/jeongm/UVACS1110-/commit/5a3ba2faf20b39db4a7acb09621e4c321f2232bf#diff-634c6fb2a2001d591560129e2171c25aR14)처럼 break함

**Comment by jeongm-in** [comment]
그러면 그냥 Flag를 써서 독자한테 이 조건에서 While loop이 돌아갑니다를 알려주고 
빠져 나갈때는 break를 하는건 괜찮다 이말이구만 
안그래도 Flag 조건을 바꿔가지고 이탈하는 걸 해봤는데 연산을 하나 더 거치더라고 
안 거치게 할 수도 있기는 한데 넘모 복잡해서 걍 break 했는데 Flag 값을 결국 안 바꿔줬다는 것이 양심에 찔리더군 
break 직전에 Flag 값을 바꿔주고 이탈하면 되긴 하겠다

**Comment by jeongm-in** [comment]
Thanks for clarification

**Comment by Bartleby2718** [comment]
오키 잘 이해했군
